/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "MyIdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "MyUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Notes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
